# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='',
  serialized_pb=_b('\n\rmessage.proto\"\x1c\n\x08GroupTag\x12\x10\n\x08JSONData\x18\x01 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GROUPTAG = _descriptor.Descriptor(
  name='GroupTag',
  full_name='GroupTag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='JSONData', full_name='GroupTag.JSONData', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=45,
)

DESCRIPTOR.message_types_by_name['GroupTag'] = _GROUPTAG

GroupTag = _reflection.GeneratedProtocolMessageType('GroupTag', (_message.Message,), dict(
  DESCRIPTOR = _GROUPTAG,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:GroupTag)
  ))
_sym_db.RegisterMessage(GroupTag)


# @@protoc_insertion_point(module_scope)
